# Generated by Django 4.0.5 on 2022-06-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsgreenteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Post', max_length=100),
        ),
    ]
